services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./data:/app/data  # Persistência do banco SQLite
      # O container do backend usará a pasta static que foi copiada para dentro dele, e as imagens de avatar salvas serão persistidas dentro do container (mas não no seu computador host, o que é um comportamento aceitável para avatares, a menos que você queira explicitamente que eles sobrevivam à recriação do container).
      # Persistência de avatares que sobrevive à recrição do container
      # - ./src/backend/static:/app/src/backend/static
    env_file:
      - .env
    environment:
      - ENV=prod
      - DB_BACKEND=sqlite
      # FRONTEND_URL precisa estar aqui para pegar o IP dinâmico via ${VM_IP}
      - FRONTEND_URL=https://${VM_IP}
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      # O frontend (Python) e o navegador precisam saber onde está a API.
      # Como estamos usando Nginx, a API está em /api no mesmo domínio/IP.
      - API_BASE_URL=https://${VM_IP}/api
      - ENV=prod
      - FRONTEND_URL=https://${VM_IP}
      - SSL_VERIFY=false
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend
    restart: always
